spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        # user-service routes
        - id: user-service
          uri: lb://USERSERVICE-DEV
          predicates:
            - Path=/user-service/users/**
          filters:
            - AuthFilter
            - RewritePath=/user-service/(?<remainingPath>.*), /${remainingPath}

        - id: user-service-swagger
          uri: lb://USERSERVICE-DEV
          predicates:
            - Path=/user-service/v3/api-docs, /user-service/swagger-ui/**
          filters:
            - RewritePath=/user-service/(?<remainingPath>.*), /${remainingPath}

        - id: user-service-auth
          uri: lb://USERSERVICE-DEV
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<remainingPath>.*), /${remainingPath}

        # blog-service routes
        - id: blog-service-swagger
          uri: lb://BLOG-SERVICE #TODO: 라우팅 경로 수정필요
          predicates:
            - Path=/blog-service/v3/api-docs, /blog-service/swagger-ui/**
          filters:
            - RewritePath=/blog-service/(?<remainingPath>.*), /${remainingPath}

        - id: blog-service
          uri: http://172.16.211.63:8080/
          predicates:
            - Path=/blog-service/**
          filters:
            - AuthFilter
            - RewritePath=/blog-service/(?<remainingPath>.*), /${remainingPath}

        # code-llm-service routes
        - id: code-llm-service-swagger
          uri: lb://CODE_LLM_SERVICE
          predicates:
            - Path=/code-llm-service/v3/api-docs, /code-llm-service/swagger-ui/**
          filters:
            - RewritePath=/code-llm-service/(?<remainingPath>.*), /${remainingPath}

        - id: code-llm-service
          uri: lb://CODE_LLM_SERVICE
          predicates:
            - Path=/code-llm-service/**
          filters:
            - AuthFilter
            - RewritePath=/code-llm-service/(?<remainingPath>.*), /${remainingPath}


        # code-compile-service routes
        - id: code-compile-service-swagger
          uri: lb://CODE-COMPILE-SERVICE
          predicates:
            - Path=/code-compile-service/v3/api-docs, /code-compile-service/swagger-ui/**
          filters:
            - RewritePath=/code-compile-service/(?<remainingPath>.*), /${remainingPath}

        - id: code-compile-service
          uri: http://172.16.211.60:18008/
          predicates:
            - Path=/code-compile-service/**
          filters:
            - AuthFilter
            - RewritePath=/code-compile-service/(?<remainingPath>.*), /${remainingPath}


        # code-bank-service routes
        - id: code-bank-service-swagger
          uri: lb://CODE-BANK-SERVICE
          predicates:
            - Path=/code-bank-service/v3/api-docs, /code-bank-service/swagger-ui/**
          filters:
            - RewritePath=/code-bank-service/(?<remainingPath>.*), /${remainingPath}

        - id: code-bank-service
          uri: http://172.16.211.69:8080/
          predicates:
            - Path=/code-bank-service/**
          filters:
            - AuthFilter
            - RewritePath=/code-bank-service/(?<remainingPath>.*), /${remainingPath}



  jwt:
    secret: ${JWT_SECRET}

server:
  port: 19091

# Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

# swagger
springdoc:
  swagger-ui:
    enabled: true
    use-root-path: true
    urls:
      - name: user-service
        url: http://172.16.211.57:19091/user-service/v3/api-docs
      - name: blog-service
        url: http://172.16.211.57:19091/blog-service/v3/api-docs
      - name: code-llm-service
        url: http://172.16.211.57:19091/code-llm-service/v3/api-docs
      - name: code-compile-service
        url: http://172.16.211.57:19091/code-compile-service/v3/api-docs
      - name: code-bank-service
        url: http://172.16.211.57:19091/code-bank-service/v3/api-docs

logging:
  level:
    org.springframework.security: TRACE
